### ISSUE TITLE
Using new viewports in theme generations does nothing

### ISSUE THREAD

**Issue by TimCrooker** [formaat-design/reshaped#270]
**Describe the bug**
I created a new theme and ran the CLI and the breakpoints are still the same as before adding the new breakpoints

**Expected behavior**
Updating the breakpoints in the selected theme should then use those breakpoints throughout the application wherever applicable

**Screenshots**
![Screenshot 2024-06-29 at 4 12 59 PM](https://github.com/formaat-design/reshaped/assets/40547057/fa067954-573b-4603-97cc-3a80a3a8e365)

![Screenshot 2024-06-29 at 4 13 22 PM](https://github.com/formaat-design/reshaped/assets/40547057/db3389cb-042b-4e03-9e8e-cc966502c05e)

**Environment (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by blvdmitry** [comment]
This happens due to how custom media queries plugin works in postcss. Since breakpoints can't be resolved in runtime and are defined during the build process, you have to pass a path to the theme defining your theme media queries values when creating postcss config: https://reshaped.so/docs/getting-started/react/installation#installation

It seems like this piece can be mentioned in a few other places too, so I'll add similar information to the theming section

**Comment by TimCrooker** [comment]
Thanks for the quick reply. I'm already passing those custom media css variables in at the top level of the application. This did not resolve the issue and it's still using the default values.

**Comment by blvdmitry** [comment]
Sorry, I meant this part. Do you use the `getConfig` function in your postcss config? 

```
const path = require("path");
const { getConfig } = require("reshaped/config/postcss");

module.exports = getConfig({
  themeMediaCSSPath: path.resolve(__dirname, "src/themes/my-theme/media.css"),
});
```

**Comment by TimCrooker** [comment]
No you're right I misread your comment on my phone. I didn't see that part of the docs. I recommend you add it in the customizing your theme documentation where it references modifying breakpoints. Thanks for the help!

**Comment by blvdmitry** [comment]
Will do, thanks!

**Comment by blvdmitry** [comment]
Added it for the upcoming major release 🙌
